//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoLaboratorio.Servico {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Laboratorio", Namespace="http://schemas.datacontract.org/2004/07/Servico")]
    [System.SerializableAttribute()]
    public partial class Laboratorio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> projetorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> qtdeAlunosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> qtdeComputadoresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sistemaOperacionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string software1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string software2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string software3Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> projetor {
            get {
                return this.projetorField;
            }
            set {
                if ((this.projetorField.Equals(value) != true)) {
                    this.projetorField = value;
                    this.RaisePropertyChanged("projetor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> qtdeAlunos {
            get {
                return this.qtdeAlunosField;
            }
            set {
                if ((this.qtdeAlunosField.Equals(value) != true)) {
                    this.qtdeAlunosField = value;
                    this.RaisePropertyChanged("qtdeAlunos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> qtdeComputadores {
            get {
                return this.qtdeComputadoresField;
            }
            set {
                if ((this.qtdeComputadoresField.Equals(value) != true)) {
                    this.qtdeComputadoresField = value;
                    this.RaisePropertyChanged("qtdeComputadores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sistemaOperacional {
            get {
                return this.sistemaOperacionalField;
            }
            set {
                if ((object.ReferenceEquals(this.sistemaOperacionalField, value) != true)) {
                    this.sistemaOperacionalField = value;
                    this.RaisePropertyChanged("sistemaOperacional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string software1 {
            get {
                return this.software1Field;
            }
            set {
                if ((object.ReferenceEquals(this.software1Field, value) != true)) {
                    this.software1Field = value;
                    this.RaisePropertyChanged("software1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string software2 {
            get {
                return this.software2Field;
            }
            set {
                if ((object.ReferenceEquals(this.software2Field, value) != true)) {
                    this.software2Field = value;
                    this.RaisePropertyChanged("software2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string software3 {
            get {
                return this.software3Field;
            }
            set {
                if ((object.ReferenceEquals(this.software3Field, value) != true)) {
                    this.software3Field = value;
                    this.RaisePropertyChanged("software3");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servico.IServico")]
    public interface IServico {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/Inserir", ReplyAction="http://tempuri.org/IServico/InserirResponse")]
        bool Inserir(ProjetoLaboratorio.Servico.Laboratorio sala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/Inserir", ReplyAction="http://tempuri.org/IServico/InserirResponse")]
        System.Threading.Tasks.Task<bool> InserirAsync(ProjetoLaboratorio.Servico.Laboratorio sala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/Listar", ReplyAction="http://tempuri.org/IServico/ListarResponse")]
        ProjetoLaboratorio.Servico.Laboratorio[] Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/Listar", ReplyAction="http://tempuri.org/IServico/ListarResponse")]
        System.Threading.Tasks.Task<ProjetoLaboratorio.Servico.Laboratorio[]> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/Editar", ReplyAction="http://tempuri.org/IServico/EditarResponse")]
        int Editar(ProjetoLaboratorio.Servico.Laboratorio sala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/Editar", ReplyAction="http://tempuri.org/IServico/EditarResponse")]
        System.Threading.Tasks.Task<int> EditarAsync(ProjetoLaboratorio.Servico.Laboratorio sala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/Excluir", ReplyAction="http://tempuri.org/IServico/ExcluirResponse")]
        int Excluir(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/Excluir", ReplyAction="http://tempuri.org/IServico/ExcluirResponse")]
        System.Threading.Tasks.Task<int> ExcluirAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/getById", ReplyAction="http://tempuri.org/IServico/getByIdResponse")]
        ProjetoLaboratorio.Servico.Laboratorio getById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServico/getById", ReplyAction="http://tempuri.org/IServico/getByIdResponse")]
        System.Threading.Tasks.Task<ProjetoLaboratorio.Servico.Laboratorio> getByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicoChannel : ProjetoLaboratorio.Servico.IServico, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoClient : System.ServiceModel.ClientBase<ProjetoLaboratorio.Servico.IServico>, ProjetoLaboratorio.Servico.IServico {
        
        public ServicoClient() {
        }
        
        public ServicoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Inserir(ProjetoLaboratorio.Servico.Laboratorio sala) {
            return base.Channel.Inserir(sala);
        }
        
        public System.Threading.Tasks.Task<bool> InserirAsync(ProjetoLaboratorio.Servico.Laboratorio sala) {
            return base.Channel.InserirAsync(sala);
        }
        
        public ProjetoLaboratorio.Servico.Laboratorio[] Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<ProjetoLaboratorio.Servico.Laboratorio[]> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public int Editar(ProjetoLaboratorio.Servico.Laboratorio sala) {
            return base.Channel.Editar(sala);
        }
        
        public System.Threading.Tasks.Task<int> EditarAsync(ProjetoLaboratorio.Servico.Laboratorio sala) {
            return base.Channel.EditarAsync(sala);
        }
        
        public int Excluir(int id) {
            return base.Channel.Excluir(id);
        }
        
        public System.Threading.Tasks.Task<int> ExcluirAsync(int id) {
            return base.Channel.ExcluirAsync(id);
        }
        
        public ProjetoLaboratorio.Servico.Laboratorio getById(int id) {
            return base.Channel.getById(id);
        }
        
        public System.Threading.Tasks.Task<ProjetoLaboratorio.Servico.Laboratorio> getByIdAsync(int id) {
            return base.Channel.getByIdAsync(id);
        }
    }
}
